### ISSUE TITLE
Unable to start Opentheso2 21.02 WAR

### ISSUE THREAD

**Issue by adamretter** [MOM-CNRS/Opentheso#19]
After downloading and deploying the WAR into Tomcat 9 and starting Tomcat, I see this error in the Tomcat logs when I visit localhost:8080/opentheso2

```
       Caused by: javax.el.ELException: Erreur lors de la lecture de [googleAnalytics] sur le type [fr.cnrs.opentheso.bean.setting.PreferenceBean]
                at javax.el.BeanELResolver.getValue(BeanELResolver.java:92)
                at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
                at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
                at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
                at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
                at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
                at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)
                ... 39 more
        Caused by: java.lang.NullPointerException
                at fr.cnrs.opentheso.bdd.helper.PreferencesHelper.getCodeGoogleAnalytics(PreferencesHelper.java:36)
                at fr.cnrs.opentheso.bean.setting.PreferenceBean.getGoogleAnalytics(PreferenceBean.java:70)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at javax.el.BeanELResolver.getValue(BeanELResolver.java:88)
                ... 45 more
```

The browser displays the HTTP 500 Error Page (see attached). 
![opentheso2-500](https://user-images.githubusercontent.com/1264057/108354915-68d4e200-71ea-11eb-8e54-771a79329284.png)

Please advise...

**Comment by miledrousset** [comment]
Have you installed the database and set up the conf file (hikari.properties) to match with your database? 
you have the script into /resources/install/opentheso_current.sql
then apply the update with /resources/install/maj_bdd_current2.sql

**Comment by adamretter** [comment]
@miledrousset Thank you. You are correct my database setup was incomplete.

I have now solved this through https://github.com/miledrousset/Opentheso2/pull/20
